SELECT NAME, DATETIME
FROM ANIMAL_INS
WHERE ANIMAL_ID NOT IN (
    SELECT ANIMAL_ID
    FROM ANIMAL_OUTS
)
ORDER BY DATETIME ASC
LIMIT 3;

# SELECT L.NAME, L.DATETIME, R.DATETIME
# FROM ANIMAL_INS L
# LEFT JOIN ANIMAL_OUTS R
#     ON L.ANIMAL_ID = R.ANIMAL_ID
# WHERE R.DATETIME IS NULL
# ORDER BY L.DATETIME
# LIMIT 3;