SELECT CATEGORY, SUM(TOTAL_SALES) TOTAL_SALES
FROM (
    SELECT *, SUM(SALES) TOTAL_SALES
    FROM BOOK_SALES
    WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
    GROUP BY BOOK_ID
) SUB
NATURAL JOIN BOOK
GROUP BY CATEGORY
ORDER BY 1;