SELECT `HISTORY_ID`, ROUND((1-IF(DIFF DIV 90, (
    SELECT DISCOUNT_RATE 
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
    WHERE DURATION_TYPE LIKE '90%' AND CAR_TYPE = '트럭'
), IF(DIFF DIV 30, (
    SELECT DISCOUNT_RATE 
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
    WHERE DURATION_TYPE LIKE '30%' AND CAR_TYPE = '트럭'
), IF(DIFF DIV 7,  (
    SELECT DISCOUNT_RATE 
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
    WHERE DURATION_TYPE LIKE '7%' AND CAR_TYPE = '트럭'
), 0)))/100)*DAILY_FEE*DIFF) `FEE`
FROM (
    SELECT *, DATEDIFF(END_DATE, START_DATE) + 1 DIFF
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) SUB
NATURAL JOIN CAR_RENTAL_COMPANY_CAR
WHERE CAR_TYPE = '트럭'
ORDER BY 2 DESC, 1 DESC;











# SELECT * 
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
# NATURAL JOIN (
#     SELECT * 
#     FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
#     WHERE DURATION_TYPE LIKE '7%'
# ) SUB
# WHERE DATEDIFF(END_DATE, START_DATE) + 1 BETWEEN 7 AND 29;

# SELECT * 
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
# NATURAL JOIN (
#     SELECT * 
#     FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
#     WHERE DURATION_TYPE LIKE '30%'
# ) SUB
# WHERE DATEDIFF(END_DATE, START_DATE) + 1 BETWEEN 30 AND 89;

# SELECT * 
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
# NATURAL JOIN (
#     SELECT * 
#     FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
#     WHERE DURATION_TYPE LIKE '90%'
# ) SUB
# WHERE DATEDIFF(END_DATE, START_DATE) + 1 >= 90;