name: Make Note Files

on:
  push:
    branches:
      - main

jobs:
  copy_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Create target directory if it doesn't exist
      run: |
        if [ ! -d "Notes" ]; then
          mkdir Notes
        fi

    - name: Copy README.md files
      run: |
        for file in $(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '^.+\/README\.md$'); do
          if [ ! -f "Notes/$file" ]; then
            mkdir -p "$(dirname "Notes/$file")"
            cp "$file" "Notes/$file"
          fi
        done
    
    - name: Commit and push changes
      run: |
        git add Notes/*
        if [ -n "$(git status --porcelain Notes/*)" ]; then
          git commit -m "add: update notes [ci skip]"
          git push origin main
        fi