name: Make Note Files

on:
  push:
    branches:
      - main

jobs:
  copy_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create target directory if it doesn't exist
      run: |
        if [ ! -d "Notes" ]; then
          mkdir Notes
        fi

    - name: Copy README.md files
      run: |
        for file in $(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '^.*\/README\.md$'); do
          if [ ! -f "markdown_files/$file" ]; then
            mkdir -p "$(dirname "markdown_files/$file")"
            cp "$file" "markdown_files/$file"
          fi
        done